### ISSUE TITLE
Abandoned packages used

### ISSUE THREAD

**Issue by ro0NL** [jakzal/toolbox#117]
```
Package halleck45/phpmetrics is abandoned, you should avoid using it.
Use phpmetrics/phpmetrics instead.

Package edsonmedina/php_testability is abandoned, you should avoid using it.
No replacement was suggested.
```

Spotted in the build :angel:

**Comment by jakzal** [comment]
Yeah, saw it.

We could drop php testability easily as it doesn't bring much value.

The phpmetrics warning is coming from another dependency though (perhaps a dev one).
