### ISSUE TITLE
[DX] Tools curation

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/toolbox#12]
Moved from https://github.com/jakzal/phpqa/issues/92

Since the added value with this image is the selection and discovery of actually valuable PHP related QA and similar tools (which you might not know about), it might make sense to make that more prominent.

1. For example, there are tools which don't seem to work:
```
$ phpqa churn run

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, boolean given, called in /tools/.composer/vendor-bin/tools/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php on line 81 and defined in /tools/.composer/vendor-bin/tools/vendor/symfony/yaml/Yaml.php:76
```
2. There are also tools which were added, but in the meantime a better candidate for the same task appeared, example `phpca` vs. [ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker)
3. some tools might be obsoleted upstream in the meantime

What I propose is this:
1. [ ] introduce a way to **mark tools as broken or deprecated** (with optional suggestion for an alternative)
2. [x] introduce a way to **tag tools** (with tags such as `composer`, `util`, `analysis`, `style`, `test`, `phpstan`, etc).
3. [x] introduce a way to **list tools by tag**, example `phpqa list style`
4. [ ] introduce a way to provide a **short help about the tool**, example `phpqa info phpstan-doctrine` would explain how to enable it, with even a short example
5. [x] have a bit of a nicer CLI for the listing (can we use Symfony Console here?)

It would probably be best if we separated tools out ftom the JSON into something else to make it more maintainable in te future.

Overall, I think this project might gain some traction as other projects start using it for their CI more so it would benefit from these kind of small tweaks which raise the value quite a bit.

WDYT?

**Comment by jakzal** [comment]
I'm pleased to announce [Toolbox v1.0.0 was just released](https://github.com/jakzal/toolbox/releases/tag/v1.0.0). It provides some of the above wish list items.

**Comment by dkarlovi** [comment]
@jakzal I saw the release. :1st_place_medal: \o/

About the remaining ones, I agree with your [point](https://github.com/jakzal/phpqa/issues/92#issuecomment-415783593):
> it's a small step from providing instructions how to enable a tool, to enabling It automatically

but still probably best to introduce that first step, even to just see the use cases more clearly. Maybe the auto-enable part could be driven by [Rector](https://github.com/rectorphp/rector) (which we planned to add anyway)?

I still think marking tools broken / abandoned + suggest alternatives would be beneficial to end users as it gives them actionable information.

**Comment by jakzal** [comment]
> but still probably best to introduce that first step, even to just see the use cases more clearly. Maybe the auto-enable part could be driven by Rector (which we planned to add anyway)?

I'm more worried about maintenance both these steps will bring rather than the amount of work these features will introduce ;)

> I still think marking tools broken / abandoned + suggest alternatives would be beneficial to end users as it gives them actionable information

It's just a matter of tagging tools, and then excluding broken ones from installation. 

If we decide to remove a tool, I would also suggest using a tag, so the tool would remain on the list for historical reasons, but would not be installed.

**Comment by dkarlovi** [comment]
> I'm more worried about maintenance both these steps will bring rather than the amount of work these features will introduce ;)

I view it as "inline documentation", as in "what's the least amount of information required to use a tool?" 

Example: if you want to enable PHPStan's extension, use `$snippet`, all other info is available upstream.

Maybe auto-management is a bit too much for now.

> It's just a matter of tagging tools, and then excluding broken ones from installation.

Agreed.

> If we decide to remove a tool, I would also suggest using a tag, so the tool would remain on the list for historical reasons, but would not be installed.

Agreed here too. :+1:

**Comment by jakzal** [comment]
It's been almost two years since the last comment and not much has happened. I'm going to assume it's good the way it is now ;)
