### ISSUE TITLE
toolbox install behind a proxy

### ISSUE THREAD

**Issue by ylebret** [jakzal/toolbox#131]
Hi,

I'm trying to build a custom phpqa docker image on a server behind a proxy but the command `php toolbox install` (I think but maybe I'm mistaken) fail with the following error :

Error: file_get_contents(https://box-project.github.io/box2/manifest.json): failed to open stream: Connection timed out

I bypassed the error by adding a php script with a stream context, and loaded the script with auto_prepend_file (php.ini) in the Dockerfile, but I don't think this is a long-term solution.

Regards,
Yannick

**Comment by jakzal** [comment]
Have you tried exporting env variables? `HTTP_PROXY` and/or `HTTPS_PROXY`?

**Comment by ylebret** [comment]
Hi,

Yes, via the build-arg option of the doccker command, and it is working as intended but it seems the file_get_contents function doesn't use them.

Regards,
Yannick

**Comment by jakzal** [comment]
Quick test locally confirms environment these variables are picked up by toolbox:

```
COMPOSER_HOME=$(pwd)/local/composer PATH=$(pwd)"/local:"(pwd)"/local/composer/vendor/bin:$PATH" HTTP_PROXY=localhost:3128 HTTPS_PROXY=localhost:3128 php ./bin/toolbox.php install --target-dir ./local --tag pre-installation
```

How does your docker file look like?

**Comment by jakzal** [comment]
Closing due to lack of feedback. Let's look at it again if someone comes up with more details.
