### ISSUE TITLE
Enable back packages disabled on PHP 7.4

### ISSUE THREAD

**Issue by jakzal** [jakzal/toolbox#170]
As part of #157 some packages had to be disabled:

- [x] phpmd
- [x] pdepend

**Comment by hussainweb** [comment]
I am not sure what was the error you faced with phpmd; however, there is a [new release of phpmd](https://github.com/phpmd/phpmd/releases/tag/2.8.1) and this might have fixed the problems. Do you mind checking or give me instructions so that I could check sometime soon?

**Comment by jakzal** [comment]
Thanks for the tip!

**Comment by jakzal** [comment]
Both phpmd and pdepend are now available on PHP 7.4.
