### ISSUE TITLE
Tag all the tools

### ISSUE THREAD

**Issue by jakzal** [jakzal/toolbox#27]
1. Come up with a list of tags we'd like to introduce (share suggestions in comments).
2. Tag the tools.

**Comment by kkreft** [comment]
Some tags proposals:
1. architecture
2. behat
3. benchmarking
4. composer
5. design-patterns
6. formatting
7. phar
8. refactoring
9. security
10. static-analysis
11. testing
12. phpstan
13. phpunit

**Comment by jakzal** [comment]
One other tag I'd like to suggest is "featured", which would include tools which we think are definitely worth checking out. These tools will need to be actively maintained and stable.

I'm only not sure about the name for this tag.

**Comment by kkreft** [comment]
It's not so bad, what other options do we have?

* awarded
* promising
* suggested

None of those sound more convincingly. IMO

**Comment by jakzal** [comment]
I'll start with featured: https://github.com/jakzal/toolbox/pull/30

**Comment by jakzal** [comment]
As part of splitting tools into smaller groups, I also tagged them with the group name.

I think it's sufficient for current use cases.

Feel free to send PRs to introduce additional tags if needed.
