### ISSUE TITLE
Symbol "~" in created symlinks from ComposerBinCommand

### ISSUE THREAD

**Issue by neradp** [jakzal/toolbox#275]
`return \sprintf(
            'ln -sf ${COMPOSER_HOME:-"~/.composer"}/vendor-bin/%s/vendor/bin/%s %s',
            $this->namespace,
            $this->source,
            $this->target
        );`

This code results at unusable symlinks.

Please replace "~" with the content of HOME variable.

**Comment by neradp** [comment]
Sorry for my later response.

I cannot "execute" symbolic links that contain **~** symbol.  I need links with full path. I can define COMPOSER HOME, which corrects the link path, but it coud be done with replacing ~ symbol with the content of HOME enviroment var.

**Comment by jakzal** [comment]
Which  operating system are you on?

**Comment by neradp** [comment]
Iam using docker containers from Devilbox project: https://github.com/devilbox/docker-php-fpm.
They are based on some debian distro.

**Comment by jakzal** [comment]
> I cannot "execute" symbolic links that contain ~ symbol. I need links with full path. I can define COMPOSER HOME, which corrects the link path, but it coud be done with replacing ~ symbol with the content of HOME enviroment var.

Looks like this a fair solution right now. Not sure when/if I'll get time to work on a different one soon.

**Comment by jakzal** [comment]
Could you show the output of `ls -l /tools` please?

**Comment by jakzal** [comment]
I'm going to close due to lack of feedback. Feel free to provide more information and we'll reopen.
