### ISSUE TITLE
Add PHP-Fuzzer

### ISSUE THREAD

**Issue by jdreesen** [jakzal/toolbox#330]
@nikic created a fuzzing tool for PHP code: https://github.com/nikic/PHP-Fuzzer

The project is still very young, but maybe it could be added at some time.

**Comment by mihai-stancu** [comment]
This works via `phive install nikic/PHP-Fuzzer` (is unsigned).

**Comment by mihai-stancu** [comment]
I can add it.

**Comment by mihai-stancu** [comment]
@jdreesen I added a PR for `php-fuzzer` but it's based on a branch that adds `phive` which is currently blocked by an external issue.

I'll ping-back here once it's unblocked.
