### ISSUE TITLE
Rector latest version unlock

### ISSUE THREAD

**Issue by benr77** [jakzal/toolbox#333]
Rector is currently locked to a previous version because of a bug.
https://github.com/jakzal/toolbox/pull/309

It looks as though this bug is now sorted. Additionally, I'm getting a weird issue running rector from the latest `phpqa` which I'm hoping will be fixed by using the latest rector which is now on version 0.9.x (the bug it was locked against was in 0.8.x).

The error I'm getting is 

```
Fatal error: Uncaught _HumbugBox9a2b3b20a128\Nette\InvalidArgumentException: Service '0190': Class or interface 'PHPStan\Type\Doctrine\DescriptorRegistry' not found. in phar:///tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/rector/vendor/nette/di/src/DI/Definitions/Definition.php:52
Stack trace:
#0 phar:///tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/rector/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(46): _HumbugBox9a2b3b20a128\Nette\DI\Definitions\Definition->setType('PHPStan\\Type\\Do...')
#1 phar:///tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/rector/vendor/nette/di/src/DI/Extensions/ServicesExtension.php(67): _HumbugBox9a2b3b20a128\Nette\DI\Definitions\ServiceDefinition->setType('PHPStan\\Type\\Do...')
#2 phar:///tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/rector/vendor/nette/di/src/DI/Extensions/ServicesExtension.php(51): _HumbugBox9a2b3b20a128\Nette\DI\Extensions\ServicesExtension->updateServiceDefinition(Object(_HumbugBox9a2b3b2 in phar:///tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/rector/vendor/nette/di/src/DI/Extensions/ServicesExtension.php on line 54
```

Thanks

**Comment by jakzal** [comment]
Thanks for the nudge :)

Feel free to submit a PR next time!

**Comment by benr77** [comment]
Thanks for the fast response. I was looking at making a PR but was working out the two repository setup.

Am I right in thinking that I need to 

- fork `jakzal/toolbox` and make changes to e.g. the rector version
- clone `jakzal/phpaq` and then get it to use my fork of the toolbox repo
- build phpqa via the Makefile?

It would be good to add this info to the Contributing section on the README

Cheers

**Comment by jakzal** [comment]
All you need to do in such a scenario is to send a pull request to `jakzal/toolbox`. It's where tools are managed.

Tests can be run locally with `make test test-integration`, or you can let github actions run them when you submit the PR.
