### ISSUE TITLE
Add codeception

### ISSUE THREAD

**Issue by hason** [jakzal/toolbox#348]
https://codeception.com

**Comment by mihai-stancu** [comment]
I can add it.

**Comment by mihai-stancu** [comment]
@jakzal unfortunately codeception won't work with `phive` because they host their phar on their own website without metadata and `phive` can't deduce any version info from it (it's also unsigned).

**Comment by jakzal** [comment]
@mihai-stancu I guess we'll need to use phar download with this one :)
