### ISSUE TITLE
Relative symlinks in TOOLS_TARGET_DIR

### ISSUE THREAD

**Issue by mihai-stancu** [jakzal/toolbox#374]
Hi,

I was trying to build an image based on yours using docker multi-stage builds. I wanted to move the tools from `/tools` to somewhere else but their symlinks are full paths and moving them would break the links.

Did you use a full path approach because various tools aren't giving you enough control over the exact symlink?

**Comment by jakzal** [comment]
The location of symlink is controlled with `--target-dir` toolbox option. 

I think @dkarlovi has some experience with moving tools around and/or multistage builds.

**Comment by mihai-stancu** [comment]
Thank you!
