### ISSUE TITLE
Cannot run with composer docker image

### ISSUE THREAD

**Issue by atrakic** [jakzal/toolbox#389]
I have existing symfony project wanted to give it a try with latest `composer` image:

docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp composer:latest bash
bash-5.1# php -v
PHP 8.0.6 (cli) (built: May  7 2021 20:48:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
bash-5.1# curl -s https://api.github.com/repos/jakzal/toolbox/releases/latest \
  | grep "browser_download_url.*toolbox.phar" \
  | cut -d '"' -f 4 \
  | xargs curl -Ls -o toolbox \
  && chmod +x toolbox
bash-5.1# ./toolbox install
You are already using the latest available Composer version 2.1.1 (stable channel).
/usr/local/bin/phive
Changed current directory to /tmp
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Using version ^1.4 for bamarni/composer-bin-plugin
./composer.json has been updated
Running composer update bamarni/composer-bin-plugin
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file
Nothing to install, update or remove
Generating autoload files
Changed current directory to /tmp
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   No executable gpg binary found. 
[ERROR]    Either install gpg or enable the gnupg extension in PHP.

**Comment by jakzal** [comment]
The image you use has no gpg installed. You'll need it to run phive, which is used to install a big number of tools.

Check out one of phpqa images for other dependencies you might need:

https://github.com/jakzal/phpqa/blob/caaa720cd3476c436e3e8de01a089f2017d72fac/debian/Dockerfile#L9-L11

https://github.com/jakzal/phpqa/blob/caaa720cd3476c436e3e8de01a089f2017d72fac/alpine/Dockerfile#L9-L11
