### ISSUE TITLE
New twig (3.x) linter

### ISSUE THREAD

**Issue by newmedia** [jakzal/toolbox#411]
Is it possible to add this linter?
https://github.com/sserbin/twig-linter

**Comment by jakzal** [comment]
Sure.

If anyone would like to pick this up, it should be added to https://github.com/jakzal/toolbox/blob/master/resources/checkstyle.json

Since twig-linter's recommended way is to use composer, we should use the composer-bin-plugin installation strategy in toolbox.

**Comment by newmedia** [comment]
@jakzal i created a pull request! and put it in the linter.json instead of the checkstyle.json

**Comment by jakzal** [comment]
Fixed by #412 #417
