### ISSUE TITLE
Updates to Phive-managed tools

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/toolbox#425]
Not sure how exactly this works, but what's the workflow to update Phive based tools?

For example, [most recent Infection is 0.26.8](https://github.com/infection/infection/releases/tag/0.26.8).

Infection in the most recent Docker image `jakzal/phpqa:1.69.3-php8.1-alpine` is 0.21.5. How do those tools get updated?

**Comment by dkarlovi** [comment]
Note, I've found this:
https://github.com/jakzal/toolbox/blob/e588e21598d51cd51d8649d309b86989f66daedf/resources/test.json#L34-L38

in the meantime, but not sure how exactly it's meant to be updated? Where does the signature and the versions come from?

**Comment by jakzal** [comment]
Phive should always install the latest. Not sure if we need a restriction here. `^` means something else in pre `1.x` versions.

**Comment by dkarlovi** [comment]
Maybe a blurb how to do the update for Phive sourced tools might allow some updates to happen.

I agree we should probably allow Phive to install latest by default.

**Comment by jakzal** [comment]
I have removed most (all? ;) ) of constraints from tools installed with phive now https://github.com/jakzal/toolbox/pull/428
