### ISSUE TITLE
Update infection tool

### ISSUE THREAD

**Issue by laurent-thireau** [jakzal/toolbox#468]
Hello,

In your composer file, the version of the infection package is 0.25.4 while a new version is available: 0.26.0.
Can you update it?
Thank you
Laurent
PS : Sorry for my english...

**Comment by jakzal** [comment]
I'm not planning to update it at this time. I'm sure there was a reason why it's locked that I don't remember.

I'm not sure why you requested it by the way, but the version in composer.json does not impact the version installed by Toolbox nor phpqa.

**Comment by laurent-thireau** [comment]
Thank you for your reply

**Comment by jakzal** [comment]
@laurent-thireau I'm not sure why it was important to you, but I have updated the infection dependency for this project now.
