### ISSUE TITLE
PHPUnit 9 support

### ISSUE THREAD

**Issue by dgoosens** [jakzal/toolbox#473]
hello @jakzal 

PHPUnit 10 now is the default version...  
So we no longer have support for PHPUnit9 in the toolbox.

Created a PR to add PHPUnit9 support, like it is the case for PHPUnit8  
https://github.com/jakzal/toolbox/pull/472

**Comment by jakzal** [comment]
Released as part of [v1.72.0](https://github.com/jakzal/toolbox/releases/tag/v1.72.0).
