### ISSUE TITLE
Support for twig-cs-fixer

### ISSUE THREAD

**Issue by babaorum** [jakzal/toolbox#497]
First of all, thank you for this awesome set of tool to use.

From my current understanding, most of the heavy work for having those tools inside phpqa is done in this repository.

I am interested in adding [twig-cs-fixer](https://github.com/VincentLanglet/Twig-CS-Fixer) to the list.
I saw that there are already several twig linter supported.
This package is now quoted in the official documentation of twig https://twig.symfony.com/doc/3.x/coding_standards.html

If it would be ok for you, I can try to open a pull request with this.

Thank you in advance.

**Comment by jakzal** [comment]
Thank you for the suggestion and the pull request 👍
