### ISSUE TITLE
Psalm PHPUnit plugin

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/toolbox#99]
https://github.com/psalm/phpunit-psalm-plugin

**Comment by ro0NL** [comment]
As of PHPUnit 8 is it still needed? Asking, since psalm-annotations are built-in upstream now: https://github.com/sebastianbergmann/phpunit/blob/0d5379adebbfde18710b076acc9550eb6a328b48/src/Framework/TestCase.php#L1087-L1091

**Comment by dkarlovi** [comment]
@ro0NL fair point, might be worth it if you're using something which can't use > 7 (BC breaks, IIRC).

**Comment by ro0NL** [comment]
long-term i think the ecosystem is better of withh built-in (psalm) types upstream; not having more plugins :sweat_smile: Though agree this might be needed meanwhile.

Same for #105 , i believe @Ocramius is a on a mission a add types to Doctrine upstream, but im not sure it'll target 2.x.

**Comment by dkarlovi** [comment]
Yes, but again, the plugin is available now to current codebases, no reason not to include it. It's easy enough to remove both of them later when they're no longer needed (and probably not maintained).

**Comment by dkarlovi** [comment]
Done in #252.
